### ISSUE TITLE
Update ari_scores

### ISSUE THREAD

**Issue by Nyecarr** [microsoft/topologic#10]
- Move into a module called similarity at topologic.similarity
- Add support for Jaccard similarity
- Remove calculate_ari_scores function (no more enriched graphs)

**Comment by dwaynepryce** [comment]
After some more thought it doesn't make sense to use Jaccard at all; it's superficially a good choice to add but it doesn't inherently take into consideration label names changing, which is pretty much a guaranteed.  I'm not sure jaccard would make sense for any of the comparisons we're trying to do re: cluster or partition membership as a result of our embedding clustering algorithms or our global partitioning algorithms.
