### ISSUE TITLE
Laplacian Spectral Embedding multiple dimension test fails on Mac OS

### ISSUE THREAD

**Issue by Nyecarr** [microsoft/topologic#35]
- tests/embedding/test_laplacian_spectral_embedding.py -> test_laplacian_embedding_elbowcut_none

This test fails on Mac OS in the github matrix action to run tests on Linux, Windows and Mac OS. The Linux and Windows tests return exactly as expected. I could not reproduce this issue on Mac OS Catalina running Python 3.7.

It is unclear to me whether this is an issue in the code, sklearn, or Github actions. Reproducible steps would be ideal for tracking down the source of this issue.

Marked resolved when we can remove the pytest.skip() from that test.

**Comment by dwaynepryce** [comment]
I also wonder if we should add something to the test where it only skips it on github actions; that way people with macOS actually could run the test.  Maybe check an env variable too and set one in the github job prior to running pytest
